[colors.bright]
black = "#969896"
blue = "#3971ed"
cyan = "#3971ed"
green = "#198844"
magenta = "#a36ac7"
red = "#cc342b"
white = "#7276F8"
yellow = "#fba922"

[colors.normal]
black = "#ffffff"
blue = "#3971ed"
cyan = "#3971ed"
green = "#198844"
magenta = "#a36ac7"
red = "#cc342b"
white = "#c5c8c6"
yellow = "#fba922"

[colors.primary]
background = "#ffffff"
foreground = "#000000"

[colors.selection]
background = "#d5baff"
foreground = "CellForeground"

[font]
size = 14

[font.offset]
x = 0
y = 2

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bw"
key = "W"
mods = "Command"

[scrolling]
history = 10000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[terminal.shell]
args = ["-l", "-c", "tmux"]
program = "/bin/zsh"

[window.padding]
x = 0
y = 0

[general]
live_config_reload = true

[[keyboard.bindings]]
key = "1"
mods = "Command"
chars = "\u001b1"

[[keyboard.bindings]]
key = "1"
mods = "Command"
chars = "\u001b1"

[[keyboard.bindings]]
key = "1"
mods = "Command"
chars = "\u001b1"

[[keyboard.bindings]]
key = "2"
mods = "Command"
chars = "\u001b2"

[[keyboard.bindings]]
key = "3"
mods = "Command"
chars = "\u001b3"

[[keyboard.bindings]]
key = "4"
mods = "Command"
chars = "\u001b4"

[[keyboard.bindings]]
key = "5"
mods = "Command"
chars = "\u001b5"

[[keyboard.bindings]]
key = "6"
mods = "Command"
chars = "\u001b6"

[[keyboard.bindings]]
key = "7"
mods = "Command"
chars = "\u001b7"

[[keyboard.bindings]]
key = "8"
mods = "Command"
chars = "\u001b8"

[[keyboard.bindings]]
key = "9"
mods = "Command"
chars = "\u001b9"
